repos:
  - repo: https://github.com/rubocop/rubocop
    rev: v1.56.4
    hooks:
      - id: rubocop
        additional_dependencies:
          - rubocop-performance
          - rubocop-rails
          - rubocop-rspec
          - standard
          - standard-rails
