development:
  adapter: postgresql
  username: jkessler1
  password: simplepass
  database: dev-team-001-local

test:
  adapter: postgresql
  username: jkessler1
  password: simplepass
  database: test-team-001-local